// We wrote App as the boot sequence that wires all modules together in the
// correct order after the Pano2VR player has finished loading its configuration.
// The Pano2VR player (pano2vr_player.js) and skin (skin.js) are generated by
// Pano2VR — we wait for the player's 'configloaded' event before touching
// any pano.* API calls.
(function (Nav) {
  'use strict';

  function App() {}

  App.prototype.boot = function () {
    Nav.LoadingOverlay.create();
    Nav.LoadingOverlay.show('Waiting for panorama player...');
    waitForPlayer(function () {
      pano.addListener('configloaded', function () {
        Nav.App._init();
      });
    });
  };

  App.prototype._init = function () {
    Nav.LoadingOverlay.show('Loading tour data...');

    Nav.XmlLoader.load('pano.xml')
      .then(function (doc) {
        var nodes = Nav.NodeParser.parse(doc);
        Nav.AppState.nodes = nodes;
        Nav.AppState.graph = Nav.GraphBuilder.build(nodes);

        // We log isolated nodes here at startup because a broken hotspot link
        // in Pano2VR will silently create an island that Dijkstra can never reach.
        var conn = Nav.GraphBuilder.checkConnectivity(Nav.AppState.graph);
        if (conn.isolated.length) {
          console.warn('[App] ' + conn.isolated.length + ' isolated nodes:', conn.isolated);
        }

        Nav.SearchPanel.buildIndex();

        // We fetch issue types from Supabase before building the UI so the
        // dropdown is driven by what is in the DB. The result is stored on
        // AppState so UIBuilder can read it without knowing about IssueService.
        return Nav.IssueService.fetchTypes().then(function (types) {
          Nav.AppState.issueTypes = types;

          Nav.StyleInjector.inject();
          Nav.UIBuilder.build();
          Nav.LoadingOverlay.create();
          Nav.Renderer.init();

          Nav.App._bindPlayerEvents();
          Nav.App._wireEvents();

          Nav.LiveController.init();
          Nav.LiveController.bindEvents();

          Nav.LoadingOverlay.setMessage('Preloading images...');
          return Promise.all([
            waitForPanoReady(),
            Nav.Preloader.preload(doc, function (loaded, total) {
              Nav.LoadingOverlay.setMessage('Preloading images ' + loaded + '/' + total);
            })
          ]).then(function () {
            Nav.AppState.navReady = true;
            Nav.LoadingOverlay.hide();
          });
        });
      })
      .catch(function (err) {
        console.error('[App] Failed to load pano.xml:', err);
        Nav.LoadingOverlay.setMessage('Failed to load tour data. ' + (err && err.message ? err.message : ''));
      });
  };

  App.prototype._bindPlayerEvents = function () {
    if (!pano || typeof pano.addListener !== 'function') return;

    // We listen to 'changenode' on the Pano2VR-generated player to know when
    // the user has moved to a different panorama node.
    pano.addListener('changenode', function () {
      if (!Nav.AppState.navActive || !Nav.AppState.activeRoute) return;
      var newId = pano.getCurrentNode();
      Nav.Navigator.handleNodeChange(newId);
    });

    // We reset the idle timer on any interaction so the camera doesn't
    // auto-re-aim at the hotspot while the user is actively looking around.
    var container = document.getElementById('container');
    if (!container) return;
    ['mousedown', 'touchstart', 'mousemove'].forEach(function (evt) {
      container.addEventListener(evt, function () {
        var state = Nav.AppState;
        if (!state.navActive || !state.activeRoute || !state.autoRotateDone) return;
        var next = state.activeRoute.path[state.stepIndex + 1];
        if (next) Nav.AutoRotator.resetIdleTimer(next.pan, next.tilt);
      }, { passive: true });
    });
  };

  App.prototype._wireEvents = function () {
    Nav.EventBus.on('nav:start', function (destId) {
      Nav.Navigator.start(destId);
    });
  };

  // We poll for window.pano every 50 ms because the Pano2VR player script sets
  // it asynchronously after parsing its configuration — there is no load event
  // we can rely on across all Pano2VR versions.
  function waitForPlayer(cb) {
    if (window.pano) { cb(); return; }
    setTimeout(function () { waitForPlayer(cb); }, 50);
  }

  // We wait for either the first 'changenode' event or a 1.8 s timeout before
  // marking the panorama ready — this covers the case where the first node
  // never fires 'changenode' because the player starts there by default.
  function waitForPanoReady() {
    return new Promise(function (resolve) {
      var done = false;
      function finish() { if (!done) { done = true; resolve(); } }
      setTimeout(finish, 1800);
      if (pano && typeof pano.addListener === 'function') {
        pano.addListener('changenode', finish);
      }
    });
  }

  Nav.App = new App();

})(window.Nav = window.Nav || {});
